---
name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: 1.26.6

    - name: Test
      run:  go test -v -tags=release -cover ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
